Update repo to new name.

diff --git a/wercker.yml b/wercker.yml
--- a/wercker.yml
+++ b/wercker.yml
@@ -22,17 +22,17 @@ build:
             composer global require drush/drush:7.1.* --no-interaction
             # Configure Drush.
             mkdir -p ~/.drush
-            cp ./wercker/nyccampdemo.aliases.drushrc.php ~/.drush
+            cp ./wercker/tecci.aliases.drushrc.php ~/.drush
             ln -s ~/.composer/vendor/bin/drush /usr/bin/drush
             # Drupal settings.
             cp ./wercker/wercker.settings.secret.php ./settings/settings.secret.php
             # Configure Apache.
-            cp ./wercker/nyccampdemo.dev.conf /etc/apache2/sites-available/
-            a2ensite nyccampdemo.dev
+            cp ./wercker/tecci.dev.conf /etc/apache2/sites-available/
+            a2ensite tecci.dev
             a2enmod rewrite
             service apache2 restart
             # Edit hosts file.
-            echo "127.0.0.1 nyccampdemo.dev" >> /etc/hosts
+            echo "127.0.0.1 tecci.dev" >> /etc/hosts
 
             # Prepare Drupal Installation and Install it.
             # Build the Drupal site and set files permissions.
@@ -42,7 +42,7 @@ build:
             ./node_modules/.bin/aquifer extensions-load
             chown -R www-data:www-data ./build/sites/default/files
             # Set alias.
-            drush site-set @nyccampdemo.nyccampdemo.dev
+            drush site-set @tecci.tecci.dev
             drush cc drush
             # Start mysql and apache servers.
             service apache2 start
@@ -50,7 +50,7 @@ build:
             # Create Drupal DB
             mysql -u root -pAdmin2015 -e "create database drupal;"
             # Install Drupal and disable sendmail.
-            /usr/bin/env PHP_OPTIONS="-d sendmail_path=`which true`" drush si -y nyccampdemo
+            /usr/bin/env PHP_OPTIONS="-d sendmail_path=`which true`" drush si -y tecci
             # Post build configuration.
             drush cc drush
             drush master-set-current-scope local
@@ -67,9 +67,9 @@ build:
             # ESLint.
             ./node_modules/.bin/gulp eslint
             # Overridden features.
-            drush @nyccampdemo.nyccampdemo.dev fl | grep -qi 'overridden' && (echo 'Overridden Features FAIL' && exit 1) || (echo 'Overridden Features PASS' && exit 0)
+            drush @tecci.tecci.dev fl | grep -qi 'overridden' && (echo 'Overridden Features FAIL' && exit 1) || (echo 'Overridden Features PASS' && exit 0)
             # Available updates.
-            drush @nyccampdemo.nyccampdemo.dev ups | grep -qi "update available" && (echo 'Updates available FAIL' && exit 1) || (echo 'No updates available PASS' && exit 0)
+            drush @tecci.tecci.dev ups | grep -qi "update available" && (echo 'Updates available FAIL' && exit 1) || (echo 'No updates available PASS' && exit 0)
             # Behat tests.
             ./vendor/bin/behat -p wercker
 deploy:
@@ -116,17 +116,17 @@ deploy:
             mkdir -p ~/.drush
             cp ./wercker/policy.drush.inc ~/.drush/
             echo 'Set sftp'
-            terminus site set-connection-mode --site=nyccampdemo --env=dev --mode=sftp
-            terminus drush --site=nyccampdemo --env=dev "cc drush --strict=0"
-            terminus drush --site=nyccampdemo --env=dev "si --account-pass=admin -y nyccampdemo --strict=0"
+            terminus site set-connection-mode --site=tecci --env=dev --mode=sftp
+            terminus drush --site=tecci --env=dev "cc drush --strict=0"
+            terminus drush --site=tecci --env=dev "si --account-pass=admin -y tecci --strict=0"
             echo 'Set git'
-            terminus site set-connection-mode --site=nyccampdemo --env=dev --mode=git
+            terminus site set-connection-mode --site=tecci --env=dev --mode=git
             # Post build configuration.
-            terminus drush --site=nyccampdemo --env=dev "cc drush --strict=0"
-            terminus drush --site=nyccampdemo --env=dev "master-set-current-scope development --strict=0"
-            terminus drush --site=nyccampdemo --env=dev "master-execute -y --strict=0"
-            terminus drush --site=nyccampdemo --env=dev "cc all --strict=0"
-            terminus drush --site=nyccampdemo --env=dev "en -y pantheon_api --strict=0"
+            terminus drush --site=tecci --env=dev "cc drush --strict=0"
+            terminus drush --site=tecci --env=dev "master-set-current-scope development --strict=0"
+            terminus drush --site=tecci --env=dev "master-execute -y --strict=0"
+            terminus drush --site=tecci --env=dev "cc all --strict=0"
+            terminus drush --site=tecci --env=dev "en -y pantheon_api --strict=0"
 deploy-test:
     steps:
     - script:
@@ -161,7 +161,7 @@ deploy-test:
     - script:
         name: Deploy code to test
         code: |
-            terminus site deploy --site=nyccampdemo --env=test --sync-content --note="Deployed from wercker UI"
+            terminus site deploy --site=tecci --env=test --sync-content --note="Deployed from wercker UI"
     - script:
         name: Deploy steps to pantheon test
         code: |
@@ -170,15 +170,15 @@ deploy-test:
             mkdir -p ~/.drush
             cp ./wercker/policy.drush.inc ~/.drush/
             # Post build configuration.
-            terminus drush --site=nyccampdemo --env=test "sqlsan -y --strict=0"
-            terminus drush --site=nyccampdemo --env=test "cc drush --strict=0"
-            terminus drush --site=nyccampdemo --env=test "master-set-current-scope test --strict=0"
-            terminus drush --site=nyccampdemo --env=test "master-execute -y --strict=0"
-            terminus drush --site=nyccampdemo --env=test "updb -y --strict=0"
-            terminus drush --site=nyccampdemo --env=test "cc all --strict=0"
-            terminus drush --site=nyccampdemo --env=test "en -y pantheon_api --strict=0"
-            terminus drush --site=nyccampdemo --env=test "l10n-update-refresh --strict=0"
-            terminus drush --site=nyccampdemo --env=test "l10n-update --strict=0"
+            terminus drush --site=tecci --env=test "sqlsan -y --strict=0"
+            terminus drush --site=tecci --env=test "cc drush --strict=0"
+            terminus drush --site=tecci --env=test "master-set-current-scope test --strict=0"
+            terminus drush --site=tecci --env=test "master-execute -y --strict=0"
+            terminus drush --site=tecci --env=test "updb -y --strict=0"
+            terminus drush --site=tecci --env=test "cc all --strict=0"
+            terminus drush --site=tecci --env=test "en -y pantheon_api --strict=0"
+            terminus drush --site=tecci --env=test "l10n-update-refresh --strict=0"
+            terminus drush --site=tecci --env=test "l10n-update --strict=0"
 deploy-live:
     steps:
     - script:
@@ -213,7 +213,7 @@ deploy-live:
     - script:
         name: Deploy code to live
         code: |
-            terminus site deploy --site=nyccampdemo --env=live --note="Deployed from wercker UI"
+            terminus site deploy --site=tecci --env=live --note="Deployed from wercker UI"
     - script:
         name: Deploy steps to pantheon live
         code: |
@@ -222,14 +222,14 @@ deploy-live:
             mkdir -p ~/.drush
             cp ./wercker/policy.drush.inc ~/.drush/
             # Post build configuration.
-            terminus drush --site=nyccampdemo --env=live "cc drush --strict=0"
-            terminus drush --site=nyccampdemo --env=live "master-set-current-scope production --strict=0"
-            terminus drush --site=nyccampdemo --env=live "master-execute -y --strict=0"
-            terminus drush --site=nyccampdemo --env=live "updb -y --strict=0"
-            terminus drush --site=nyccampdemo --env=live "cc all --strict=0"
-            terminus drush --site=nyccampdemo --env=live "en -y pantheon_api --strict=0"
-            terminus drush --site=nyccampdemo --env=live "l10n-update-refresh --strict=0"
-            terminus drush --site=nyccampdemo --env=live "l10n-update --strict=0"
+            terminus drush --site=tecci --env=live "cc drush --strict=0"
+            terminus drush --site=tecci --env=live "master-set-current-scope production --strict=0"
+            terminus drush --site=tecci --env=live "master-execute -y --strict=0"
+            terminus drush --site=tecci --env=live "updb -y --strict=0"
+            terminus drush --site=tecci --env=live "cc all --strict=0"
+            terminus drush --site=tecci --env=live "en -y pantheon_api --strict=0"
+            terminus drush --site=tecci --env=live "l10n-update-refresh --strict=0"
+            terminus drush --site=tecci --env=live "l10n-update --strict=0"
 deploy-multidev:
     steps:
     - script:
@@ -278,18 +278,18 @@ deploy-multidev:
             echo '   StrictHostKeyChecking no' >> /root/.ssh/config
             mkdir -p ~/.drush
             cp ./wercker/policy.drush.inc ~/.drush/
-            terminus site create-env --site=nyccampdemo --to-env=$NEWBRANCH --from-env=dev
+            terminus site create-env --site=tecci --to-env=$NEWBRANCH --from-env=dev
             terminus sites aliases
             echo 'Set sftp'
-            terminus site set-connection-mode --site=nyccampdemo --env=$NEWBRANCH --mode=sftp
-            terminus drush --site=nyccampdemo --env=$NEWBRANCH "cc drush --strict=0"
-            terminus drush --site=nyccampdemo --env=$NEWBRANCH "si --account-pass=admin -y nyccampdemo --strict=0"
+            terminus site set-connection-mode --site=tecci --env=$NEWBRANCH --mode=sftp
+            terminus drush --site=tecci --env=$NEWBRANCH "cc drush --strict=0"
+            terminus drush --site=tecci --env=$NEWBRANCH "si --account-pass=admin -y tecci --strict=0"
             echo 'Set git'
-            terminus site set-connection-mode --site=nyccampdemo --env=$NEWBRANCH --mode=git
+            terminus site set-connection-mode --site=tecci --env=$NEWBRANCH --mode=git
             # Post build configuration.
-            terminus drush --site=nyccampdemo --env=$NEWBRANCH "cc drush --strict=0"
-            terminus drush --site=nyccampdemo --env=$NEWBRANCH "master-set-current-scope development --strict=0"
-            terminus drush --site=nyccampdemo --env=$NEWBRANCH "master-execute -y --strict=0"
-            terminus drush --site=nyccampdemo --env=$NEWBRANCH "cc all --strict=0"
-            terminus drush --site=nyccampdemo --env=$NEWBRANCH "en -y pantheon_api --strict=0"
-            echo "If everything worked, go to http://$NEWBRANCH-nyccampdemo.pantheonsite.io"
+            terminus drush --site=tecci --env=$NEWBRANCH "cc drush --strict=0"
+            terminus drush --site=tecci --env=$NEWBRANCH "master-set-current-scope development --strict=0"
+            terminus drush --site=tecci --env=$NEWBRANCH "master-execute -y --strict=0"
+            terminus drush --site=tecci --env=$NEWBRANCH "cc all --strict=0"
+            terminus drush --site=tecci --env=$NEWBRANCH "en -y pantheon_api --strict=0"
+            echo "If everything worked, go to http://$NEWBRANCH-tecci.pantheonsite.io"
